name: virtual_assistant
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  animated_splash_screen: ^1.3.0
  page_transition: ^2.0.9
  persistent_bottom_nav_bar: ^5.0.2
  get_cli: ^1.8.1
  flutter_speed_dial: ^6.2.0
  intl: ^0.17.0
  date_time_picker_widget: ^1.0.1+4
  fluttertoast: ^8.1.2
  month_year_picker: ^0.2.0+3
  animated_toggle_switch: ^0.6.1
  flutter_local_notifications: 13.0.0
  flutter_native_timezone: 2.0.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/icons/
  fonts: 
    - family: BottomNavIcon
      fonts: 
        - asset: assets/font/BottomNavIcon.ttf
    - family: DrawerIcon
      fonts: 
        - asset: assets/font/DrawerIcon.ttf
    - family: UpperScrollBar
      fonts: 
        - asset: assets/font/UpperScrollBar.ttf
  uses-material-design: true

